### ISSUE TITLE
Task not serializable 任务无法序列化的错误

### ISSUE THREAD

**Issue by luckuan** [luckuan/blogs#4]
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:304)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:294)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:122)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2055)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1827)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1922)
	at HdfsWriter$.main(HdfsWriter.scala:78)
	at HdfsWriter.main(HdfsWriter.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.io.NotSerializableException: org.apache.spark.SparkContext
Serialization stack:
	- object not serializable (class: org.apache.spark.SparkContext, value: org.apache.spark.SparkContext@6ba76c0f)
	- field (class: HdfsWriter$$anonfun$2, name: sc$1, type: class org.apache.spark.SparkContext)
	- object (class HdfsWriter$$anonfun$2, <function2>)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:101)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:301)
	... 13 more

**Comment by luckuan** [comment]
错误原因是在task任务的代码中调用的SparkContext，因此对SparkContext序列化的时候，属性SparkContext也会序列化，导致错误。

错误的代码：

    //在每个executor上执行的函数
    //此处定义的是,针对每个分区,我们把计算好的结果写入到本地目录中
    val func = (tc: TaskContext, it: Iterator[String]) => {
      //输出文件路径
      val outFilePath = s"${basePath}/${tc.partitionId()}"

      //****************开始往文件中写数据********************//
      //得到文件系统
      //      val fs = FileSystem.get(broadcastedConf.value)
      val fs = FileSystem.get(sc.hadoopConfiguration)

**Comment by luckuan** [comment]
解决方案是把sc从task的代码的去除
