### ISSUE TITLE
调用Lzop的接口直接创建hadoop的文件报错

### ISSUE THREAD

**Issue by luckuan** [luckuan/blogs#5]
16/03/09 11:12:06 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on yz-hd-0013.meilishuo.com:48081 (size: 749.0 B, free: 1616.1 MB)
16/03/09 11:12:06 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, yz-hd-nn2.meilishuo.com): java.lang.IllegalAccessError: tried to access class com.hadoop.compression.lzo.LzoCompressor from class com.hadoop.compression.lzo.LzoUtils$
	at com.hadoop.compression.lzo.LzoUtils$.getLzopOutputStream(LzoUtils.scala:23)
	at com.hadoop.compression.lzo.HdfsWriter$$anonfun$1.apply(HdfsWriter.scala:51)
	at com.hadoop.compression.lzo.HdfsWriter$$anonfun$1.apply(HdfsWriter.scala:36)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

16/03/09 11:12:06 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 2, yz-hd-nn2.meilishuo.com, PROCESS_LOCAL, 2090 bytes)
16/03/09 11:12:07 INFO TaskSetManager: Lost task 1.0 in stage 0.0 (TID 1) on executor yz-hd-0013.meilishuo.com: java.lang.IllegalAccessError (tried to access class com.hadoop.compression.lzo.LzoCompressor from class com.hadoop.compression.lzo.LzoUtils$) [duplicate 1]

**Comment by luckuan** [comment]
原因：
com.hadoop.compression.lzo.LzoCompressor 不是public方法，不能直接创建。如果自己创建com.hadoop.compression.lzo，在包里对其进行封装，编译是没有问题的，但是由于hadoop大部分存在hadoop-lzo.jar包，因此会导致上面的异常。

解决方法：
 val lzopCodec = new LzopCodec()
      lzopCodec.setConf(new Configuration())
      val lzoIndexOuputStream = lzopCodec.createIndexedOutputStream(fs.create(dstPath),fs.create(dstIndexPath))

Lzo通过可以通过其的方式来得到outputstream，不用自己来创建LzoCompressor实例，避免了上述的问题。
